search_rules:
    query: snow colorado -is:retweet has:media

search_params:
    results-per-call: 100
    max-tweets: 1000
    expansions: author_id,referenced_tweets.id,referenced_tweets.id.author_id,attachments.media_keys
    tweet-fields: id,created_at,author_id,text
    user-fields: description
    media-fields: type,url
    place-fields: full_name
    polls-fields: options

output_params:
    save_file: True
    filename_prefix: snow-photos
    results_per_file: 100000
